package com.android.gastos.ui.theme

import androidx.compose.ui.graphics.Color

// Base Material 3 seed palette (money-green seed) for devices without dynamic color.
val PrimaryLight = Color(0xFF146C43)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA6F3C4)
val OnPrimaryContainerLight = Color(0xFF002111)
val SecondaryLight = Color(0xFF4C6358)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE9D9)
val OnSecondaryContainerLight = Color(0xFF092018)
val TertiaryLight = Color(0xFF3D6373)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E8FB)
val OnTertiaryContainerLight = Color(0xFF001F29)
val BackgroundLight = Color(0xFFFBFDF8)
val OnBackgroundLight = Color(0xFF191D1A)
val SurfaceLight = Color(0xFFFBFDF8)
val OnSurfaceLight = Color(0xFF191D1A)
val SurfaceVariantLight = Color(0xFFDCE5DC)
val OnSurfaceVariantLight = Color(0xFF404943)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val OutlineLight = Color(0xFF707972)

val PrimaryDark = Color(0xFF8AD6A7)
val OnPrimaryDark = Color(0xFF00391E)
val PrimaryContainerDark = Color(0xFF00522D)
val OnPrimaryContainerDark = Color(0xFFA6F3C4)
val SecondaryDark = Color(0xFFB2CCBE)
val OnSecondaryDark = Color(0xFF1E352A)
val SecondaryContainerDark = Color(0xFF344B40)
val OnSecondaryContainerDark = Color(0xFFCEE9D9)
val TertiaryDark = Color(0xFFA5CCDF)
val OnTertiaryDark = Color(0xFF04343F)
val TertiaryContainerDark = Color(0xFF244B5A)
val OnTertiaryContainerDark = Color(0xFFC1E8FB)
val BackgroundDark = Color(0xFF10140F)
val OnBackgroundDark = Color(0xFFE0E4DD)
val SurfaceDark = Color(0xFF10140F)
val OnSurfaceDark = Color(0xFFE0E4DD)
val SurfaceVariantDark = Color(0xFF404943)
val OnSurfaceVariantDark = Color(0xFFC0C9C0)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val OutlineDark = Color(0xFF8A938C)
